# fly.toml app configuration file generated for datingappferenc on 2023-05-17T12:06:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingappferenc"
primary_region = "lhr"

[build]
  image = "ferencweb/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dfecbnq6s"
  CloudinarySettings__ApiKey="141126963745337"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
